name: CI

on:
  push:
    branches:
      - main
      - master
      - assignment-testing
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out code
        uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Setting up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Installing npm dependencies
        run: npm ci

      - name: Running linter
        run: npm run lint

      - name: Running tests
        run: npm test